# Generated by Django 5.2.8 on 2025-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'superadmin'), ('admin', 'admin'), ('user', 'user')], default='user', max_length=20),
        ),
    ]
