# Generated by Django 5.2.8 on 2025-11-30 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian vehicle number', regex='^[A-Z]{2}[0-9]{2}[A-Z]{1,3}[0-9]{1,4}$')])),
                ('vehicle_type', models.CharField(choices=[('Two', 'Two Wheelers'), ('Three', 'Three Wheelers'), ('Four', 'Four Wheelers')], max_length=5)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
